Phoner/routes.py
from crypt import methods
from flask import Blueprint, current_app, render_template, session, redirect, request, url_for, flash
import functools
import uuid

from dataclasses import asdict
from Phoner.models import Notification, User,Survey, Question, Contact,ScheduledMessage, SentMessage, OpenSurvey
from Phoner.forms import ExtendedNotificationForm, NotificationForm, RegisterForm, LoginForm, SurveyForm, QuestionForm, UpdateContacts

from twilio.rest import Client
from twilio.twiml.messaging_response import MessagingResponse
import requests
import time
import os
from dotenv import load_dotenv
from bson.objectid import ObjectId
import pandas as pd
from datetime import datetime, timedelta

load_dotenv()



from passlib.hash import pbkdf2_sha256
pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


###Utilities          

@pages.cli.command()
def scheduled():
    
    scheduledMessages = current_app.db.ScheduledMessage.find()
    
    for message in scheduledMessages:
        scheduledDate = datetime.strptime(message["date"], "%Y-%m-%d").date()
        if scheduledDate == datetime.now().date():
            
            query = {}

            
            if message["age"]:
                age_min, age_max = message["age"].split("-")
                query["age"] = {"$gte": int(age_min), "$lte": int(age_max)}
            
            if message["gender"]:
                query["gender"] = message["gender"]

            if message["kids"]:
                query["kids"] = message["kids"]

            if message["education"]:
                query["education"] = message["education"]

            if message["village"]:
                query["village"] = message["village"]

            
            contacts = current_app.db.Contacts.find(query) 
                    
           
            notification = current_app.db.Notifications.find_one({"_id": message["messageId"]})
            for number in contacts:
                results = send_message(number, notification["content"],"whatsapp" )
                sentmessage = SentMessage(
            _id=uuid.uuid4().hex,
            nors="Notification",
            date=datetime.datetime.now(),
            response=results
        )
                current_app.db.SentMessages.insert_one(asdict(sentmessage)) 
                current_app.db.ScheduledMessage.delete_one({"_id": message._id})
            

def send_message(number, _message,type):
    account_sid = os.environ.get("TWILIO_SID")
    auth_token = os.environ.get("AUTH_TOKEN") 
    client = Client(account_sid, auth_token)

    #set a state/user variable for which platform to use whatsapp or sms
    platform = type.lower()
    message = client.messages.create( 
                              from_=f'{platform}:+14155238886',  
                              body=f'{_message}',      
                              to=f'{platform}:{number}' 
                          ) 
    #sentmessage = SentMessage(
    #        _id=uuid.uuid4().hex,
    #        project=number,
    #        date=datetime.now(),
    #        response=message.sid #store more meaningfull input 
    #    )
   
    #current_app.db.SentMessages.insert_one(asdict(sentmessage)) 
    
    return message.sid


def login_required(route):  
    @functools.wraps(route)  #function that replaces any end-point and runs a login check
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper

@pages.route("/")

def index():
   

    return render_template(
        "index.html",
        title="Phoner"
       
    )




##USER ENDPOINTS
@pages.route("/register", methods=["GET", "POST"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        current_app.db.Users.insert_one(asdict(user))

        flash("User registered successfully", "success") 
    

        return redirect(url_for(".login"))

    return render_template(
        "register.html", title="Phoner Marketing - Register", form=form
    )

@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = current_app.db.Users.find_one({"email": form.email.data})
        if not user_data:
            flash("Login credentials not correct", category="danger")
            return redirect(url_for(".login"))
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))

        flash("Login credentials not correct", category="danger")

    return render_template("login.html", title="Phoner Marketing - Login", form=form)

@pages.route("/logout", methods=["GET", "POST"])
def logout():
    current_theme = session.get("theme")
    session.clear()
    session["theme"] = current_theme
    return redirect(url_for(".index"))



##SEND AND RECIEVE ENDPOINTS




@pages.route("/survey_recieve", methods=['GET','POST'])
def survey_recieve(): 
    print("its a hit")
    #process input and filter
    number = request.values.get("From", "")
    number = number.lstrip("whatsapp:")
    print(number)
    multi = request.values
    print(multi)
    
    incoming_msg = request.values.get('Body', '').lower()
    resp = MessagingResponse()
    msg = resp.message()
    responded = False
    
    #insert the phone number from Twilio
    survey = current_app.db.OpenSurvey.find_one({"contact": number})
    if survey:
        current_app.db.OpenSurvey.update_one({"_id": survey["_id"]}, {"$push": {"responses": incoming_msg}})
        survey = current_app.db.OpenSurvey.find_one({"contact": number})
        opensurvey = OpenSurvey(
            contact=survey["contact"],
            questions=survey["questions"],
            responses=survey["responses"])
        responseNumber = len(survey["responses"])
      
        if len(survey["questions"]) == len(survey["responses"]):
            
            send_message(survey["contact"],"Thank you for completing the survey. We have Credited your account with 25 shillings","whatsapp")
            current_app.db.CompletedSurvey.insert_one(asdict(opensurvey))
            current_app.db.OpenSurvey.delete_one({"contact": number})
            
        else:
            send_message(survey["contact"],survey["questions"][responseNumber],"whatsapp")
            print("message sent")
    
        


    
 
    

    # what to return?
    return str(msg)

#delete








@pages.route("/schedule/", methods=["GET", "POST"])
#require login
def schedule():
    if request.method == 'POST':
        
        

        sm = ScheduledMessage(
            _id=uuid.uuid4().hex,
             age = request.form["age-group"],
            gender = request.form["gender"],
            kids = request.form["kids"],
            education = request.form["education"],
            village = request.form["village"],
            messageId = request.form["messageId"],
            #time = request.form["time"],
            date = request.form["date"],
            nors = request.form["nors"],
        )
        

        current_app.db.ScheduledMessage.insert_one(asdict(sm))
        
    
    #return render_template("scheduled_messages.html", scheduled_data=scheduled_data)
    return redirect(url_for(".scheduled_messages"))

@pages.route("/schedule/<string:_id>/delete", methods=["GET", "POST"])
#require login
def schedule_delete(_id):
    current_app.db.ScheduledMessage.delete_one({"_id": _id})


    return redirect(url_for(".scheduled_messages"))

    
@pages.route("/scheduled_messages", methods=["GET", "POST"])
def scheduled_messages():
    scheduled_data = current_app.db.ScheduledMessage.find({})   
    #all_schedule = [ScheduledMessage(**x) for x in scheduled_data]
    #print(all_schedule)
    return render_template("scheduled_messages.html", scheduled_data=scheduled_data)
    

@pages.route("/delete_scheduled_messages", methods=["GET", "POST"])
def delete_scheduled_messages():
    #delete the message selected
    #pass remaining list of messages
    return redirect("scheduled_messages.html")


####### API Contact calls

@pages.route("/contacts")
def contacts():
    contacts = current_app.db.Contacts.find({})
    #sms_db_content = current_app.db.Questions.find({}) #remember to update questions to the proper database
    all_contacts = [Contact(**x) for x in contacts]
    
    return render_template("contacts.html", all_contacts=all_contacts)


@pages.route("/contacts_delete/", methods=["GET", "POST"])
#require login
def contacts_delete():
    #delete
    current_app.db.Contacts.delete_many({})
    return redirect(url_for(".contacts"))

@pages.route("/contacts_update/", methods=["GET", "POST"])
#require login
def contacts_update():
    form = UpdateContacts()
    
    if request.method == 'POST':
         if form.validate_on_submit():
            print(form.ASSET_UID.data,form.update_type.data,form.note.data)
            if form.ASSET_UID.data:
                ASSET_UID = form.ASSET_UID.data

                TOKEN = os.environ.get("AUTH_KOBO_Token")
                KF_URL = 'kobo.humanitarianresponse.info' #or 'kf.kobotoolbox.org'
                #ASSET_UID = 'afS4VYAKGa25JCqigdiCKv' #asset id of the project gotten from the url e.g. https://kobo.humanitarianresponse.info/#/forms/axXYMX67noGAR9i4HNNMUR/summary - TOOL specifc
                #QUERY = '{"start":{"$gt":"2022-10-10"}}' # query for filtering results  https://www.mongodb.com/docs/manual/reference/operator/query/#query-selectors

Phoner/templates/macros/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
  {{ field.label(class_="form__label") }} {{ field(class_="form__field")}} {%-
  for error in field.errors %}
  <span class="form__error">{{ error }}</span>
  {% endfor %}
</div>
{% endmacro %} {% macro render_area_field(field) %}
<div class="form__group">
  {{ field.label(class_="form__label") }} {{ field(rows=4, class_="form__field",
  style="resize: none") }} {%- for error in field.errors %}
  <span class="form__error">{{ error }}</span>
  {% endfor %}
</div>
{% endmacro %} {% macro render_select_field(field) %}
<div class="form__group">
  {{ field.label(class_="form__label") }} {{ field(class="form-control") }} {%-
  for error in field.errors %}
  <span class="form__error">{{ error }}</span>
  {% endfor %}
</div>
{% endmacro %}

Phoner/templates/macros/footer.html
{% macro footer() %}
<footer class="footer">
    <small>Copyright &copy;2022. Phoner Marketing. All rights reserved.</small>
</footer>
{% endmacro %}

Phoner/templates/macros/nav.html
{% from "macros/svgs.html" import moon, sun %} {%macro header(email, theme) %}

<header class="header">
  <div class="nav-container">
    <a href="{{url_for('pages.index')}}" class="header__logo">
      <svg class="logo__icon" height="100" width="100">
        <circle
          cx="50"
          cy="50"
          r="40"
          stroke="black"
          stroke-width="3"
          fill="red"
        />
        Sorry, your browser does not support inline SVG.
      </svg>
      <span class="logo__name"> Phoner</span>
    </a>

    <nav class="nav">
      {% if not email %}
      <a
        href="{{ url_for('pages.login') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.login') }}"
      >
        <span class="nav__item">Log in</span>
      </a>
      <a
        href="{{ url_for('pages.register') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.register') }}"
      >
        <span class="nav__item">Register</span>
      </a>
      {% else %}
      <a
        href="{{ url_for('pages.dataroom') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.dataroom') }}"
      >
        <span class="nav__item">Data Room</span>
      </a>
      <a
        href="{{ url_for('pages.contacts') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.contacts') }}"
      >
        <span class="nav__item">Contacts</span>
      </a>
      <a
        href="{{ url_for('survey.center') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('survey.center') }}"
      >
        <span class="nav__item">Survey Center</span>
      </a>

      <a
        href="{{ url_for('notification.center') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.index') }}"
      >
        <span class="nav__item">Notification Center</span>
      </a>
      <a href="{{ url_for('pages.logout') }}" class="nav__link">
        <span class="nav__item">Log out</span>
      </a>
      {% endif %}

      <a
        href="{{ url_for('pages.toggle_theme', current_page=request.path) }}"
        class="nav__link"
      >
        <span class="nav__item">
          {% if theme == "dark" %} {{ sun("nav__icon") }} {% else %} {{
          moon("nav__icon") }} {% endif %}
        </span>
      </a>
    </nav>
  </div>
</header>

{% endmacro %}

Phoner/templates/macros/svgs.html
{% macro star(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
</svg>
{% endmacro %}

{% macro pencil(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
</svg>
{% endmacro %}

{% macro moon(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
</svg>
{% endmacro %}

{% macro sun(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
</svg>
{% endmacro %}