Phoner/routes.py
from crypt import methods
from flask import Blueprint, current_app, render_template, session, redirect, request, url_for, flash
import functools
import uuid

from dataclasses import asdict
from Phoner.models import Notification, User,Survey, Question, Contact,ScheduledMessage, SentMessage, OpenSurvey
from Phoner.forms import ExtendedNotificationForm, NotificationForm, RegisterForm, LoginForm, SurveyForm, QuestionForm, UpdateContacts

from twilio.rest import Client
from twilio.twiml.messaging_response import MessagingResponse
import requests
import time
import os
from dotenv import load_dotenv
from bson.objectid import ObjectId
import pandas as pd
from datetime import datetime, timedelta

load_dotenv()



from passlib.hash import pbkdf2_sha256
pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


###Utilities          

@pages.cli.command()
def scheduled():
    
    scheduledMessages = current_app.db.ScheduledMessage.find()
    
    for message in scheduledMessages:
        scheduledDate = datetime.strptime(message["date"], "%Y-%m-%d").date()
        if scheduledDate == datetime.now().date():
            
            query = {}

            
            if message["age"]:
                age_min, age_max = message["age"].split("-")
                query["age"] = {"$gte": int(age_min), "$lte": int(age_max)}
            
            if message["gender"]:
                query["gender"] = message["gender"]

            if message["kids"]:
                query["kids"] = message["kids"]

            if message["education"]:
                query["education"] = message["education"]

            if message["village"]:
                query["village"] = message["village"]

            
            contacts = current_app.db.Contacts.find(query) 
                    
           
            notification = current_app.db.Notifications.find_one({"_id": message["messageId"]})
            for number in contacts:
                results = send_message(number, notification["content"],"whatsapp" )
                sentmessage = SentMessage(
            _id=uuid.uuid4().hex,
            nors="Notification",
            date=datetime.datetime.now(),
            response=results
        )
                current_app.db.SentMessages.insert_one(asdict(sentmessage)) 
                current_app.db.ScheduledMessage.delete_one({"_id": message._id})
            

def send_message(number, _message,type):
    account_sid = os.environ.get("TWILIO_SID")
    auth_token = os.environ.get("AUTH_TOKEN") 
    client = Client(account_sid, auth_token)

    #set a state/user variable for which platform to use whatsapp or sms
    platform = type.lower()
    message = client.messages.create( 
                              from_=f'{platform}:+14155238886',  
                              body=f'{_message}',      
                              to=f'{platform}:{number}' 
                          ) 
    #sentmessage = SentMessage(
    #        _id=uuid.uuid4().hex,
    #        project=number,
    #        date=datetime.now(),
    #        response=message.sid #store more meaningfull input 
    #    )
   
    #current_app.db.SentMessages.insert_one(asdict(sentmessage)) 
    
    return message.sid


def login_required(route):  
    @functools.wraps(route)  #function that replaces any end-point and runs a login check
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper

@pages.route("/")

def index():
   

    return render_template(
        "index.html",
        title="Phoner"
       
    )




##USER ENDPOINTS
@pages.route("/register", methods=["GET", "POST"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        current_app.db.Users.insert_one(asdict(user))

        flash("User registered successfully", "success") 
    

        return redirect(url_for(".login"))

    return render_template(
        "register.html", title="Phoner Marketing - Register", form=form
    )

@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = current_app.db.Users.find_one({"email": form.email.data})
        if not user_data:
            flash("Login credentials not correct", category="danger")
            return redirect(url_for(".login"))
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))

        flash("Login credentials not correct", category="danger")

    return render_template("login.html", title="Phoner Marketing - Login", form=form)

@pages.route("/logout", methods=["GET", "POST"])
def logout():
    current_theme = session.get("theme")
    session.clear()
    session["theme"] = current_theme
    return redirect(url_for(".index"))



##SEND AND RECIEVE ENDPOINTS




@pages.route("/survey_recieve", methods=['GET','POST'])
def survey_recieve(): 
    print("its a hit")
    #process input and filter
    number = request.values.get("From", "")
    number = number.lstrip("whatsapp:")
    print(number)
    multi = request.values
    print(multi)
    
    incoming_msg = request.values.get('Body', '').lower()
    resp = MessagingResponse()
    msg = resp.message()
    responded = False
    
    #insert the phone number from Twilio
    survey = current_app.db.OpenSurvey.find_one({"contact": number})
    if survey:
        current_app.db.OpenSurvey.update_one({"_id": survey["_id"]}, {"$push": {"responses": incoming_msg}})
        survey = current_app.db.OpenSurvey.find_one({"contact": number})
        opensurvey = OpenSurvey(
            contact=survey["contact"],
            questions=survey["questions"],
            responses=survey["responses"])
        responseNumber = len(survey["responses"])
      
        if len(survey["questions"]) == len(survey["responses"]):
            
            send_message(survey["contact"],"Thank you for completing the survey. We have Credited your account with 25 shillings","whatsapp")
            current_app.db.CompletedSurvey.insert_one(asdict(opensurvey))
            current_app.db.OpenSurvey.delete_one({"contact": number})
            
        else:
            send_message(survey["contact"],survey["questions"][responseNumber],"whatsapp")
            print("message sent")
    
        


    
 
    

    # what to return?
    return str(msg)

#delete








@pages.route("/schedule/", methods=["GET", "POST"])
#require login
def schedule():
    if request.method == 'POST':
        
        

        sm = ScheduledMessage(
            _id=uuid.uuid4().hex,
             age = request.form["age-group"],
            gender = request.form["gender"],
            kids = request.form["kids"],
            education = request.form["education"],
            village = request.form["village"],
            messageId = request.form["messageId"],
            #time = request.form["time"],
            date = request.form["date"],
            nors = request.form["nors"],
        )
        

        current_app.db.ScheduledMessage.insert_one(asdict(sm))
        
    
    #return render_template("scheduled_messages.html", scheduled_data=scheduled_data)
    return redirect(url_for(".scheduled_messages"))

@pages.route("/schedule/<string:_id>/delete", methods=["GET", "POST"])
#require login
def schedule_delete(_id):
    current_app.db.ScheduledMessage.delete_one({"_id": _id})


    return redirect(url_for(".scheduled_messages"))

    
@pages.route("/scheduled_messages", methods=["GET", "POST"])
def scheduled_messages():
    scheduled_data = current_app.db.ScheduledMessage.find({})   
    #all_schedule = [ScheduledMessage(**x) for x in scheduled_data]
    #print(all_schedule)
    return render_template("scheduled_messages.html", scheduled_data=scheduled_data)
    

@pages.route("/delete_scheduled_messages", methods=["GET", "POST"])
def delete_scheduled_messages():
    #delete the message selected
    #pass remaining list of messages
    return redirect("scheduled_messages.html")


####### API Contact calls

@pages.route("/contacts")
def contacts():
    contacts = current_app.db.Contacts.find({})
    #sms_db_content = current_app.db.Questions.find({}) #remember to update questions to the proper database
    all_contacts = [Contact(**x) for x in contacts]
    
    return render_template("contacts.html", all_contacts=all_contacts)


@pages.route("/contacts_delete/", methods=["GET", "POST"])
#require login
def contacts_delete():
    #delete
    current_app.db.Contacts.delete_many({})
    return redirect(url_for(".contacts"))

@pages.route("/contacts_update/", methods=["GET", "POST"])
#require login
def contacts_update():
    form = UpdateContacts()
    
    if request.method == 'POST':
         if form.validate_on_submit():
            print(form.ASSET_UID.data,form.update_type.data,form.note.data)
            if form.ASSET_UID.data:
                ASSET_UID = form.ASSET_UID.data

                TOKEN = os.environ.get("AUTH_KOBO_Token")
                KF_URL = 'kobo.humanitarianresponse.info' #or 'kf.kobotoolbox.org'
                #ASSET_UID = 'afS4VYAKGa25JCqigdiCKv' #asset id of the project gotten from the url e.g. https://kobo.humanitarianresponse.info/#/forms/axXYMX67noGAR9i4HNNMUR/summary - TOOL specifc
                #QUERY = '{"start":{"$gt":"2022-10-10"}}' # query for filtering results  https://www.mongodb.com/docs/manual/reference/operator/query/#query-selectors

Phoner/templates/contacts_update_form.html
{% from "macros/fields.html" import render_text_field, render_area_field,
render_select_field %} {% extends "layout.html" %} {%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}

<form name="add_movie" method="post" novalidate class="form">
  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.ASSET_UID) }}
    {{render_area_field(form.note) }} {{ render_select_field(form.update_type
    )}}

    <div>{{ form.submit(class_="button button--form") }}</div>
  </div>
</form>

{% endblock %}

Phoner/templates/dataroom.html
{% extends 'layout.html' %}

{% block head_content %}
<link rel='stylesheet' href="{{ url_for('static', filename='css/index.css') }}" />

{% endblock %}

{% block main_content %}


<section class='body'>
    <h1 class='headline'> Phoner Data Room</h1>
<div>
    <canvas id='myChart'></canvas>
  </div>
  
  <script src='https://cdn.jsdelivr.net/npm/chart.js'></script>
  
  <script>
    const ctx = document.getElementById('myChart');
  
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: {{data | safe}},
        datasets: [{
          label: '# of Messages Sent',
          data: {{data | safe}},
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  </script>
  





    <section class='control'>
        <a href='{{ url_for("pages.scheduled_messages") }}' class='button button--control'>
            <span>See All Scheduled Messages</span>
        </a>
        
        
        </section>



</section>
    {% endblock %}

Phoner/templates/index.html
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}" />
{% endblock %}

{% block main_content %}

<section class="body">
    <h1 class="headline"> Phoner Marketing</h1>




{% if session['email'] %}

   <b>Please add graphs displaying marketing campaign status</b>
{% else %}
    <p class="table__empty">You haven't logged in so there is no data to display.  <a href="{{ url_for('pages.register') }}" class="link">Login or create an account to get started!</a></p>
{% endif %}



</section>
    {% endblock %}

Phoner/templates/login.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="login" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}

        <div class="form__container">
            {{ form.hidden_tag() }}
    
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
    
            <span class="form__small">
                Don't have an account? <a href="{{ url_for('pages.register') }}" class="form__link">Register here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

Phoner/templates/notification.html
{% from "macros/fields.html" import render_text_field %} {% extends
"layout.html" %} {%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/sms.css') }}" />
{% endblock %} {% block main_content %}

<section class="content">
  {% with messages = get_flashed_messages(with_categories=true) %} {%- for
  category, message in messages %}
  <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
  {% endfor %} {% endwith %}
  <h1>Notifications</h1>
  <section class="control">
    <a
      href="{{ url_for('notification.notification_send') }}"
      class="button button--control"
    >
      <span>Send Notifications</span>
    </a>
    <a
      href="{{ url_for('notification.notification_schedule') }}"
      class="button button--control"
    >
      <span>Schedule Notifications</span>
    </a>
  </section>
  {% if notification_data %}

  <table class="table">
    <colgroup>
      <col style="width: 20%" />
      <col style="width: 65%" />
      <col style="width: 15%" />
    </colgroup>
    <thead>
      <tr class="table__header">
        <th class="table__cell table__cell--header">Title</th>
        <th class="table__cell table__cell--header">Content</th>
        <th class="table__cell table__cell--header"></th>
      </tr>
    </thead>
    <tbody>
      {% for notification in notification_data %}
      <tr>
        <td class="table__cell">
          <p class="table__notificationTitle">{{ notification.title }}</p>
        </td>
        <td class="table__cell">{{ notification.content }}</td>
        <td class="table__cell">
          <a
            href="{{ url_for('notification.notification_details',_id=notification._id) }}"
            class="table__link"
            >View</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="table__empty">
    You haven't added any text messages yet.
    <a href="{{ url_for('notification.add') }}" class="link">Add one!</a>
  </p>
  {% endif %}

  <a href="{{ url_for('notification.add') }}" class="button button--add">
    <span>+</span>
  </a>

  {% endblock %}
</section>

Phoner/templates/notification_new.html
{% from "macros/fields.html" import render_text_field %} {% extends
"layout.html" %} {%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}
<form name="add_notification" method="post" novalidate class="form">
  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.title) }} {{
    render_text_field(form.content) }}
    <div>{{ form.submit(class_="button button--form") }}</div>
  </div>
</form>
{% endblock %}

Phoner/templates/notification_schedule.html
{% from "macros/fields.html" import render_text_field, render_area_field,
render_select_field %} {% extends "layout.html" %} {%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}

<h1>Schdule Notifications</h1>
<form action="{{ url_for('pages.schedule') }}" method="POST">
  <label for="">Select a notification:</label>
  <select name="messageId" method="POST" action="/">
    {% for notification in notifications %}
    <option value="{{notification._id}}" selected>
      {{notification.title}}
    </option>
    " {% endfor %}
  </select>
  <label for="">When date:</label>
  <input type="date" id="date" name="date" method="POST" />
  <input id="nors" name="nors" value="notification" method="POST" hidden />

  <br />
  What filters do you want to apply?
  <br />
  <label for="age-group">Select Age Group:</label>
  <select name="age-group" id="age-group">
    <option value="">Select an option</option>
    <option value="0-18">0-18 years</option>
    <option value="19-30">19-30 years</option>
    <option value="31-50">31-50 years</option>
    <option value="51+">51+ years</option>
  </select>

  <label for="gender">Select Gender:</label>
  <select name="gender" id="gender">
    <option value="">Select an option</option>
    <option value="male">Male</option>
    <option value="female">Female</option>
    <option value="other">Other</option>
  </select>
  <label for="kids">Number of Kids:</label>
  <select name="kids" id="kids">
    <option value="">Select an option</option>
    <option value="0">None</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="3">4</option>
    <option value="4+">5 or more</option>
  </select>
  <label for="education">Select Education Level:</label>
  <select name="education" id="education">
    <option value="">Select an option</option>
    <option value="primary">Primary</option>
    <option value="secondary">Secondary</option>
    <option value="university">University</option>
    <option value="none">None</option>
  </select>

  <label for="village">Village:</label>
  <select name="village" method="POST" action="/">
    {% for village in villages %}
    <option name="village" value="{{village}}" selected>{{village}}</option>
    " {% endfor %}
  </select>
  <br />
  <input type="submit" value="Submit" />
</form>

{% endblock %}

Phoner/templates/notification_send.html
{% from "macros/fields.html" import render_text_field, render_area_field,
render_select_field %} {% extends "layout.html" %} {%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}

<form
  name="add_notification"
  method="post"
  novalidate
  class="form"
  action="{{ url_for('notification.send_notification') }}"
>
  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_select_field(form.message) }} {{
    render_select_field(form.age) }}{{ render_select_field(form.gender) }}{{
    render_select_field(form.kids) }}{{ render_select_field(form.education) }}
    {{ render_select_field(form.village) }} {{ render_select_field(form.type) }}
    <div>{{ form.submit(class_="button button--form") }}</div>
  </div>
</form>

{% endblock %}

Phoner/templates/placeholder.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}


{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}


{% block main_content %}
    <h1>Message sent - PLACEHOLDER</h1>
    
{% endblock %}

Phoner/templates/question_create.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}


{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}


{% block main_content %}
    <form name="add_notification" method="post" novalidate class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}
            {{ render_text_field(form.title) }}
            {{ render_text_field(form.content) }}
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>
{% endblock %}

Phoner/templates/survey.html
{% extends "layout.html" %} {% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/sms.css') }}" />
{% endblock %} {% block main_content %}

<section class="body__chatbot">
  <h1 class="headline">Phoner Survey and Question Platform</h1>

  <section class="control">
    <a
      href="{{ url_for('survey.survey_send') }}"
      class="button button--control"
    >
      <span>Send out Survey</span>
    </a>
    <a href="{{ url_for('survey.schedule') }}" class="button button--control">
      <span>Schedule Surveys</span>
    </a>
  </section>

  <table width="100%" height="100%">
    <tr>
      <td width="50%">
        <h2>Survey's</h2>
        {% if survey_data %}

        <table class="table">
          <colgroup>
            <col style="width: 20%" />
            <col style="width: 65%" />
            <col style="width: 15%" />
          </colgroup>
          <thead>
            <tr class="table__header">
              <th class="table__cell table__cell--header">Title</th>
              <th class="table__cell table__cell--header">Content</th>
              <th class="table__cell table__cell--header"></th>
            </tr>
          </thead>
          <tbody>
            {% for survey in survey_data %}
            <tr>
              <td class="table__cell">
                <p class="table__notificationTitle">{{ survey.title }}</p>
              </td>
              <td class="table__cell">{{ survey.content }}</td>
              <td class="table__cell">
                <a
                  href="{{ url_for('survey.survey_details',_id=survey._id) }}"
                  class="table__link"
                  >View</a
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p class="table__empty">
          You haven't added any survey's yet.
          <a href="{{ url_for('survey.add') }}" class="link">Add one!</a>
        </p>
        {% endif %}

        <a href="{{ url_for('survey.add') }}" class="button button--add1">
          <span>+</span>
        </a>
      </td>

      <td width="50%">
        <h2>Question's</h2>
        {% if question_data %}

        <table class="table">
          <colgroup>
            <col style="width: 20%" />
            <col style="width: 65%" />
            <col style="width: 15%" />
          </colgroup>
          <thead>
            <tr class="table__header">
              <th class="table__cell table__cell--header">Title</th>
              <th class="table__cell table__cell--header">Content</th>
              <th class="table__cell table__cell--header"></th>
            </tr>
          </thead>
          <tbody>
            {% for question in question_data %}
            <tr>
              <td class="table__cell">
                <p class="table__notificationTitle">{{ question.title }}</p>
              </td>
              <td class="table__cell">{{ question.content }}</td>
              <td class="table__cell">
                <a
                  href="{{ url_for('survey.question_details',_id=question._id) }}"
                  class="table__link"
                  >View</a
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p class="table__empty">
          You haven't added any question's yet.
          <a href="{{ url_for('survey.question_add') }}" class="link"
            >Add one!</a
          >
        </p>
        {% endif %}

        <a
          href="{{ url_for('survey.question_create') }}"
          class="button button--add"
        >
          <span>+</span>
        </a>
      </td>
    </tr>
  </table>
</section>
{% endblock %}

Phoner/templates/survey_question_add.html
{% extends "layout.html" %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

<td width=50%>
    <h2> Question's</h2>
    {% if question_data %}

    <table class="table">
        <colgroup>
            <col style="width: 20%">
            <col style="width: 65%">
            <col style="width: 15%">
        </colgroup>
        <thead>
            <tr class="table__header">
                <th class="table__cell table__cell--header">Title</th>
                <th class="table__cell table__cell--header">Content</th>
                <th class="table__cell table__cell--header"></th>
            </tr>
        </thead>
        <tbody>
            {% for question in question_data %}
            {% if question._id not in survey.questions %}
            <tr>
                <td class="table__cell">
                    <p class="table__notificationTitle">{{ question.title }}</p>

                </td>
                <td class="table__cell">{{ question.content }}</td>
                <td class="table__cell"><a
                        href="{{ url_for('survey.question_addq', _id=survey._id, q_id=question._id) }}"
                        class="table__link">Add</a></td>
            </tr>

            {% endif %}


            {% endfor %}

        </tbody>
    </table>
    <br>

    <input type="text" id="input">
    <button class="btn btn-dark btn-block" id="button">click</button>
    {% else %}
    <p class="table__empty">You haven't added any question's yet. <a href="{{ url_for('pages.question_add') }}"
            class="link">Add one!</a></p>
    {% endif %}




</td>

<script type="text/javascript" src="{{url_for('static',filename='list.js')}}">

</script>
{% endblock %}

Phoner/templates/survey_schedule.html
{% from "macros/fields.html" import render_text_field, render_area_field,
render_select_field %} {% extends "layout.html" %} {%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}

<h1>Schedule Surveys</h1>
<form action="{{ url_for('pages.schedule') }}" method="POST">
  <label for="">Select a Survey:</label>
  <select name="messageId" method="POST" action="/">
    {% for survey in surveys %}
    <option value="{{survey._id}}" selected>{{survey.title}}</option>
    " {% endfor %}
  </select>

  <label for="">When date:</label>
  <input type="date" id="date" name="date" method="POST" />

  <input id="nors" name="nors" value="survey" method="POST" hidden />
  <br />
  What filters do you want to apply?
  <br />
  <label for="age-group">Select Age Group:</label>
  <select name="age-group" id="age-group">
    <option value="">Select an option</option>
    <option value="0-18">0-18 years</option>
    <option value="19-30">19-30 years</option>
    <option value="31-50">31-50 years</option>
    <option value="51+">51+ years</option>
  </select>

  <label for="gender">Select Gender:</label>
  <select name="gender" id="gender">
    <option value="">Select an option</option>
    <option value="male">Male</option>
    <option value="female">Female</option>
    <option value="other">Other</option>
  </select>
  <label for="kids">Number of Kids:</label>
  <select name="kids" id="kids">
    <option value="">Select an option</option>
    <option value="0">None</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="3">4</option>
    <option value="4+">5 or more</option>
  </select>
  <label for="education">Select Education Level:</label>
  <select name="education" id="education">
    <option value="">Select an option</option>
    <option value="primary">Primary</option>
    <option value="secondary">Secondary</option>
    <option value="university">University</option>
    <option value="none">None</option>
  </select>

  <label for="village">Village:</label>
  <select name="village" method="POST" action="/">
    {% for village in villages %}
    <option name="village" value="{{village}}" selected>{{village}}</option>
    " {% endfor %}
  </select>
  <br />

  <input type="submit" value="Submit" />
</form>

{% endblock %}

<!--
<form method="POST" action="/">
    {{ form.csrf_token }}
    {{ form.name.label }} {{ form.name(size=20) }}
    <input type="submit" value="Go">
</form>-->

Phoner/templates/userdetails.html
#check https://python-web.teclado.com/section14/lectures/10_create_page_movie_details/